title: Family Recipe Book
theme: jekyll-theme-primer        # any GitHub‑hosted theme; change later if you like

collections:
  recipes:
    output: true                  # emit an HTML page per recipe
    permalink: /recipes/:name/    # pretty URLs

defaults:
  - scope:
      path: ""          # empty = all paths
      type: recipes     # applies only to the recipes collection
    values:
      layout: recipes

exclude:
  - "scripts"                     
  - "db_ssl"